#!/bin/sh
#postinst
#change ports if needed
#keep existing LE-certificates if exists
#keep cronjob for renewal if existed
#pre-calculate keys if missing

if [ -f /tmp/do_lighttpd_restart ]; then
    restart=$(cat /tmp/do_lighttpd_restart)
   #rm -f /tmp/do_lighttpd_restart
fi

echo "Preparing files and directories..."
# create needed folder for letsencrypt initial setup files
[ -d /config/letsencrypt/ ] || mkdir -p /config/letsencrypt/

if [ ! -d "/var/log/lighttpd_custom" ]; then
    mkdir /var/log/lighttpd_custom
    chown www-data:www-data /var/log/lighttpd_custom
fi

# if its not already created, create cronjob for LE
if [ ! -f "/etc/cron.monthly/letsrenew.sh" ]; then
        ln -sf /config/letsencrypt/letsrenew.sh /etc/cron.monthly/letsrenew.sh
fi

# establish config from default, if missing - avoid killing a custom setting
if [ ! -f "/config/custom/www/settings.inc" ]; then
        cp /config/custom/www/settings_default.inc /config/custom/www/settings.inc
fi
rm -f /config/custom/www/settings_default.inc

# establish config from default, if missing - avoid killing custom https-port setting
# damn! preinst deleted whole directory /config/custom, so previous config is always gone!
if [ ! -f "/config/custom/lighttpd/conf-enabled/10-ssl.conf" ]; then
    cp /config/custom/lighttpd/conf-enabled/10-ssl_default.conf /config/custom/lighttpd/conf-enabled/10-ssl.conf
    if [ -f /tmp/custom_ports ]; then
        # what is in default config
        customhttpport=$(grep -i server.port /config/custom/lighttpd/*.conf /config/custom/lighttpd/conf-enabled/*.conf | awk -F'=' {'gsub(" ","",$2);print $2;'})
        customhttpsport=$(grep -iE 'SERVER\["socket"\] == "0.0.0.0' /config/custom/lighttpd/*.conf /config/custom/lighttpd/conf-enabled/*.conf | awk -F':' {'gsub(" ","",$3);gsub("{","",$3);gsub("\"","",$3);print $3;'})
        # what was in user config
        customhttpportnew=$(cat /tmp/custom_ports | awk {'print $1'})
        customhttpsportnew=$(cat /tmp/custom_ports | awk {'print $2'})
        sed -i -r 's/server.port.{0,4}=.{0,4}'$customhttpport'/server.port = '$customhttpportnew'/' /config/custom/lighttpd/conf-enabled/10-ssl.conf
        sed -i -r 's/\]:'$customhttpport'"/\]:'$customhttpportnew'"/' /config/custom/lighttpd/conf-enabled/10-ssl.conf
        sed -i -r 's/:'$customhttpsport'"/:'$customhttpsportnew'"/' /config/custom/lighttpd/conf-enabled/10-ssl.conf
        sed -i -r 's/:'$customhttpsport'\$1"/:'$customhttpsportnew'\$1"/' /config/custom/lighttpd/conf-enabled/10-ssl.conf
       #rm -f /tmp/custom_ports
    fi
fi
rm -f cp /config/custom/lighttpd/conf-enabled/10-ssl_default.conf

# start with permissions, ignore errors
chmod 755 /config/letsencrypt/acme_tiny.py
chmod 755 /config/letsencrypt/letsrenew.sh
chmod 755 /config/letsencrypt/repair.sh
chmod 755 /config/scripts/port_81.sh
chmod 755 /config/scripts/port_8443.sh
chmod 755 /config/custom/bin/ip2dns

# change original webserver http-port from 80 to 81 in case of 80 is used for custom webserver
customhttpport=$(grep -i server.port /config/custom/lighttpd/*.conf /config/custom/lighttpd/conf-enabled/*.conf | awk -F'=' {'gsub(" ","",$2);print $2;'})
if [ $(grep -iE 'server.port.{0,4}=.{0,4}'$customhttpport /config/custom/lighttpd/conf-enabled/10-ssl.conf | wc -l) -eq 1 ] &&
   [ $(grep -iE '\]:'$customhttpport'"' /config/custom/lighttpd/conf-enabled/10-ssl.conf | wc -l) -eq 1 ] &&
   [ $(grep "http-port 80" /config/config.boot | wc -l) -eq 1 ]; then
    echo "Changing http-port from 80 to 81..."
    /config/scripts/port_81.sh
    restart=""
fi
# change original webserver https-port from 443 to 8443 in case of 443 is used for custom webserver
customhttpsport=$(grep -iE 'SERVER\["socket"\] == "0.0.0.0' /config/custom/lighttpd/*.conf /config/custom/lighttpd/conf-enabled/*.conf | awk -F':' {'gsub(" ","",$3);gsub("{","",$3);gsub("\"","",$3);print $3;'})
if [ $(grep -iE ':'$customhttpsport'"' /config/custom/lighttpd/conf-enabled/10-ssl.conf | wc -l) -eq 2 ] &&
   [ $(grep -iE ':'$customhttpsport'\$1"' /config/custom/lighttpd/conf-enabled/10-ssl.conf | wc -l) -eq 1 ] &&
   [ $(grep "https-port 443" /config/config.boot | wc -l) -eq 1 ]; then
    echo "Changing https-port from 443 to 8443..."
    /config/scripts/port_8443.sh
    restart=""
fi

# reestablish server.pem with RSA key if possible
chmod +w /etc/lighttpd/server.pem
if [ -f "/config/letsencrypt/signed.crt" ] && [ ! $(stat -c %s /config/letsencrypt/signed.crt) -eq 0 ] &&
   [ -f "/config/letsencrypt/domain.key" ] && [ ! $(stat -c %s /config/letsencrypt/domain.key) -eq 0 ]
then
  cat /config/letsencrypt/signed.crt | tee /tmp/server.pem >/dev/null
  cat /config/letsencrypt/domain.key | tee -a /tmp/server.pem >/dev/null
  if [ $(sudo sha1sum /etc/lighttpd/server.pem | awk {'print $1'}) != $(sha1sum /tmp/server.pem | awk {'print $1'}) ]; then
    restart="A"
    echo "Put cert files to server.pem"
    cp /tmp/server.pem /etc/lighttpd/server.pem
  fi
  rm -f /tmp/server.pem
elif [ -f "/config/letsencrypt/original_server.pem" ]; then
  # if not, recover original server.pem if possible
  if [ $(sudo sha1sum /etc/lighttpd/server.pem | awk {'print $1'}) != $(sha1sum /config/letsencrypt/original_server.pem | awk {'print $1'}) ]; then
    restart="B"
    echo "Recovering original server.pem file..."
    cp /config/letsencrypt/original_server.pem /etc/lighttpd/server.pem
  fi
fi

## only if restart=1, in this case try to stop first
if [ "$restart" ]; then
    echo "Stopping original webserver"
    # stop EdgeOS original Webserver if running
    if [ -f "/var/run/lighttpd.pid" ]; then
            sudo /sbin/start-stop-daemon --stop --pidfile /var/run/lighttpd.pid
            if [ -f "/var/run/lighttpd.pid" ]; then
                    rm /var/run/lighttpd.pid
            fi
    fi
    echo "Fire up original webserver..."
    # start original EdgeOS webserver
    sudo /sbin/start-stop-daemon --start --quiet \
            --pidfile /var/run/lighttpd.pid \
            --exec /usr/sbin/lighttpd -- -f /etc/lighttpd/lighttpd.conf
    echo "Restart-Reason: "$restart >/tmp/do_lighttpd_restart
fi

echo "Fire up custom webserver"
# start custom script webserver
sudo /sbin/start-stop-daemon --start --quiet \
        --pidfile /var/run/lighttpd_custom.pid \
        --exec /usr/sbin/lighttpd -- -f /config/custom/lighttpd/lighttpd_custom.conf

## calculate keys of not already there (could be done offline and in backgroud)
calcscript="/config/letsencrypt/calc.sh"
# an interrupted calculation (force-reboot) was already cleaned from preinst
# existing calc-script at this moment must be "active"
if [ -f $calcscript ]; then
    echo "Looks like calculation of keys is already in progress..."
else
    if [ ! -f "/config/letsencrypt/account.key" ] || [ $(stat -c %s /config/letsencrypt/account.key) -eq 0 ]; then
        echo "Schedule account-key generation..."
        echo "#!/bin/sh" >$calcscript
        echo "openssl genrsa 4096 | tee /config/letsencrypt/account_tmp.key" >>$calcscript
        echo "cp    /config/letsencrypt/account_tmp.key /config/letsencrypt/account.key"  >>$calcscript
        echo "rm -f /config/letsencrypt/account_tmp.key"  >>$calcscript
    fi
    if [ ! -f "/config/letsencrypt/domain.key" ] || [ $(stat -c %s /config/letsencrypt/domain.key) -eq 0 ]; then
        echo "Schedule domain-key generation..."
        if [ ! -f $calcscript ]; then
            echo "#!/bin/sh" >$calcscript
        fi
        echo "openssl genrsa 4096 | tee /config/letsencrypt/domain_tmp.key" >>$calcscript
        echo "cp    /config/letsencrypt/domain_tmp.key /config/letsencrypt/domain.key"  >>$calcscript
        echo "rm -f /config/letsencrypt/domain_tmp.key"  >>$calcscript
    fi
    if [ -f $calcscript ]; then
        echo "rm -f "$(dirname $calcscript)"/nohup.out"  >>$calcscript
        echo "rm -f "$(dirname $calcscript)"calc.sh"  >>$calcscript
        chmod 755 $calcscript
        echo "triggering openssl calculation in backgroud..."
        nohup $calcscript &
    fi
fi
echo "postinst installation finished"

exit 0
