#!/bin/sh

# Exit on error
set -e

# stop custom Webserver if running
if [ -f "/var/run/lighttpd_custom.pid" ]; then
        sudo /sbin/start-stop-daemon --stop --pidfile /var/run/lighttpd_custom.pid
        if [ -f "/var/run/lighttpd_custom.pid" ]; then
                rm /var/run/lighttpd_custom.pid
        fi
fi

# stop EdgeOS original Webserver if running
if [ -f "/var/run/lighttpd_custom.pid" ]; then
        sudo /sbin/start-stop-daemon --stop --pidfile /var/run/lighttpd.pid
        if [ -f "/var/run/lighttpd.pid" ]; then
                rm /var/run/lighttpd.pid
        fi
fi

if [ -f "/var/www/htdocs/cgi-bin-status.php" ]; then
        rm /var/www/htdocs/cgi-bin-status.php
fi

if [ -f "/var/www/htdocs/namevlans.php" ]; then
        rm /var/www/htdocs/namevlans.php
fi

# remove old custom folder with content!! (WARNING)
if [ ! -d "/config/custom/" ]
then
        rm -R /config/custom/
fi

exit 0
