#!/bin/sh

# Exit on error
set -e

if [ -f "/var/www/htdocs/cgi-bin-status.php" ]; then
        rm /var/www/htdocs/cgi-bin-status.php
fi

if [ -f "/var/www/htdocs/namevlans.php" ]; then
        rm /var/www/htdocs/namevlans.php
fi

exit 0
