#!/bin/sh

# Exit on error
#set -e

# clean up old files from previous versions
# old bmk-webstatus login button
if [ -f "/var/www/php/app/views/login.old" ]; then
    cp /var/www/php/app/views/login.old /var/www/php/app/views/login.php
    rm /var/www/php/app/views/login.old
fi
# delete old status php files
if [ -f "/var/www/htdocs/cgi-bin-status.php" ]; then
    rm /var/www/htdocs/cgi-bin-status.php
fi
if [ -f "/var/www/htdocs/namevlans.php" ]; then
    rm /var/www/htdocs/namevlans.php
fi
# CPO: delete old other files
if [ -d "/var/www/htdocs/.well-known" ]; then
    rm -R /var/www/htdocs/.well-known
fi
if [ -d "/var/www/htdocs/css" ]; then
    rm -R /var/www/htdocs/css
fi
if [ -d "/var/www/htdocs/fonts" ]; then
    rm -R /var/www/htdocs/fonts
fi
if [ -d "/var/www/htdocs/js" ]; then
    rm -R /var/www/htdocs/js
fi

# stop custom Webserver if running
if [ -f "/var/run/lighttpd_custom.pid" ]; then
        sudo /sbin/start-stop-daemon --stop --pidfile /var/run/lighttpd_custom.pid
        if [ -f "/var/run/lighttpd_custom.pid" ]; then
                rm /var/run/lighttpd_custom.pid
        fi
fi

# stop EdgeOS original Webserver if running
if [ -f "/var/run/lighttpd.pid" ]; then
        sudo /sbin/start-stop-daemon --stop --pidfile /var/run/lighttpd.pid
        if [ -f "/var/run/lighttpd.pid" ]; then
                rm /var/run/lighttpd.pid
        fi
fi

# remove old custom folder with content!! (WARNING)
# custom contains lighttpd_custom.conf, www-directory, bin/ip2dns --> will be reinstalled from package
if [ -d "/config/custom/" ]
then
        rm -R /config/custom/
fi
#CPO: cleanup old files from former versions of this package
#if [ -f "/config/scripts/post-config.d/install_letsencrypt.sh" ]; then
#        rm /config/scripts/post-config.d/install_letsencrypt.sh
#fi
if [ -f "/config/0xffstatus_restart.sh" ]; then
        rm /config/0xffstatus_restart.sh
fi
if [ -f "/config/0xffcustom_restart.sh" ]; then
        rm /config/0xffcustom_restart.sh
fi

# recover original lighttpd.conf
if [ -L /etc/lighttpd/lighttpd.conf ]; then
  # it is a link
  if [ -f /etc/lighttpd/lighttpd.old ]; then 
    ## .old files exist as well --> preferred over linked file!
    ## recover backup file
    rm /etc/lighttpd/lighttpd.conf
    cp /etc/lighttpd/lighttpd.old /etc/lighttpd/lighttpd.conf
    rm /etc/lighttpd/lighttpd.old
    ## when lighttpd.old exists, 10-ssl.old should be there as well
    if [ -f "/etc/lighttpd/conf-enabled/10-ssl.old" ]; then
      cp /etc/lighttpd/conf-enabled/10-ssl.old /etc/lighttpd/conf-enabled/10-ssl.conf
      rm /etc/lighttpd/conf-enabled/10-ssl.old
    fi
  else
    ## replace link by link-target
    cp /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd_linked.conf
    rm /etc/lighttpd/lighttpd.conf
    cp /etc/lighttpd/lighttpd_linked.conf /etc/lighttpd/lighttpd.conf
    rm /etc/lighttpd/lighttpd_linked.conf
  fi
  rm /config/lighttpd/lighttpd.conf
else
  ## link does not exist, try .old file 
  if [ -f "/etc/lighttpd/lighttpd.old" ]; then
    cp /etc/lighttpd/lighttpd.old /etc/lighttpd/lighttpd.conf
    rm /etc/lighttpd/lighttpd.old
  fi
  if [ -f "/etc/lighttpd/conf-enabled/10-ssl.old" ]; then
    cp /etc/lighttpd/conf-enabled/10-ssl.old /etc/lighttpd/conf-enabled/10-ssl.conf
    rm /etc/lighttpd/conf-enabled/10-ssl.old
  fi
fi

if [ -f "/etc/lighttpd/conf-enabled/99-bmk.conf" ]; then
  rm /etc/lighttpd/conf-enabled/99-bmk.conf
fi

exit 0
